[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/a"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/b"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200